[tool.poetry]
name = "spotify-dump"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "CC0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
spotipy = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
